cmake(bugfix):add wamr compile missing source
interpreters/wamr/wamr/core/iwasm/common/wasm_memory.c:708: undefined reference to `os_mremap'

Signed-off-by: xuxin19 <xuxin19@xiaomi.com>